[package]
name = "play-sound"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
libc = "0.2"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
